### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '../saved_models/ctrecon/AttnLNP/run_1/criterion.pt'

### ISSUE THREAD

**Issue by AIIAAI** [its-gucci/partially-observed-neural-processes#1]
Hi, Thanks for the great job. I find there're no criterion.pt file under ../saved_models/ctrecon/AttnLNP/run_1/. And I face the error:FileNotFoundError: [Errno 2] No such file or directory: '../saved_models/ctrecon/AttnLNP/run_1/criterion.pt' could you please upload the criterion.pt file? Thanks so much

**Comment by its-gucci** [comment]
Models were trained with skorch=0.8.0, which doesn't need a criterion.py file. Using this skorch version should avoid this error in the notebook.
